// Role hierarchy and permissions
const ROLES = {
  SUPERADMIN: 'SUPERADMIN',
  ADMIN: 'ADMIN',
  DOCENTE: 'DOCENTE',
  ESTUDIANTE: 'ESTUDIANTE',
};

// Role hierarchy (higher index = higher privileges)
const ROLE_HIERARCHY = [ROLES.ESTUDIANTE, ROLES.DOCENTE, ROLES.ADMIN, ROLES.SUPERADMIN];

// Reservation statuses
const RESERVATION_STATUS = {
  PENDIENTE: 'PENDIENTE',
  APROBADA: 'APROBADA',
  PARCIAL: 'PARCIAL',
  RECHAZADA: 'RECHAZADA',
  CANCELADA: 'CANCELADA',
  DEVUELTA: 'DEVUELTA',
};

// Notification types
const NOTIFICATION_TYPES = {
  RESERVA_APROBADA: 'RESERVA_APROBADA',
  RESERVA_RECHAZADA: 'RESERVA_RECHAZADA',
  RESERVA_PARCIAL: 'RESERVA_PARCIAL',
  STOCK_BAJO: 'STOCK_BAJO',
  STOCK_AGOTADO: 'STOCK_AGOTADO',
  SISTEMA: 'SISTEMA',
};

// Cycle types
const CYCLE_TYPES = {
  EXPLORATORIO: 'EXPLORATORIO',
  CONCEPTUAL: 'CONCEPTUAL',
  CONTEXTUAL: 'CONTEXTUAL',
  PROYECTIVO: 'PROYECTIVO',
};

// Audit actions
const AUDIT_ACTIONS = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  TRANSFER: 'TRANSFER',
  CANCEL: 'CANCEL',
  RETURN: 'RETURN',
};

// Pagination defaults
const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
};

module.exports = {
  ROLES,
  ROLE_HIERARCHY,
  RESERVATION_STATUS,
  NOTIFICATION_TYPES,
  CYCLE_TYPES,
  AUDIT_ACTIONS,
  PAGINATION,
};
